name: deploy do app flask no ubuntu-ge
on: push

jobs: 
  deploy: 
    runs-on: deploy-encontro5
    steps: 
      - name: checkout do repositorio
        uses: actions/checkout@v4

      - name: construcao da imagem e execucao por meio do bash 
        shell: bash
        run: bash deploy.sh
